version: "3.8"
services:
  database:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: foro-medico_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourdbpassword

  pgadmin:
    container_name: pg_container2
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-your@email.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-123yourpassword456}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"

  ruby:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/foro-medico
    ports:
      - "3000:3000"
    depends_on:
      - database

networks:
  postgres:
    driver: bridge

volumes:
    ruby:
    postgres:
    pgadmin: